# PROBLEM 1


# Introduction

In [1]:
# Say "Hello, World!" With Python
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


In [2]:
# Python If-Else
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if (n%2)==1:
        print ("Weird")
    elif (n<=5) and (n>=2):
        print ("Not Weird")
    elif (n<=20) and (n>=6):
        print ("Weird")
    else:
        print ("Not Weird")
    


5
Weird


In [3]:
# Arithmetic Operators
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print (a+b)
    print(a-b)
    print(a*b)

3
2
5
1
6


In [4]:
# Python: Division
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(int(a/b))
    print (a/b)

4
3
1
1.3333333333333333


In [5]:
# Loops
if __name__ == '__main__':
    n = int(input())
    for i in range (0,n):
        print (i**2)

5
0
1
4
9
16


In [21]:
# Write a function
def is_leap(year):
    leap = False
   
    if (year % 400)==0:
        leap =True
    elif (year % 100) == 0:
        leap = False
    elif (year % 4 ) == 0:
        leap = True
    else:
        leap = False
    
    return leap
year = int(input())
print(is_leap(year))

2000
True


In [8]:
# Print Function
if __name__ == '__main__':
    n = int(input())

    for a in range (1,n+1):
        print (a, end="")

3
123

# Data Types

In [9]:
# List Comprehensions
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    newlist= []
    for i in range(x+1):
        for j in range(y+1):
            for k in range(z+1): 
                if i+j+k != n:
                    newlist.append([i,j,k])
                
    print (newlist)

1
1
2
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2]]


In [10]:
# Find the Runner-Up Score!
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    arr_list = list(arr)
    sorted_list= sorted (arr_list, reverse=True)
    
    if len(set(sorted_list)) == 1: #this line is searched on chatgpt (how to check if all the items
                                   #in a list are the same)
        print (sorted_list [0])
        
        
    elif n >2 and len(sorted_list)>=2:
        while sorted_list[0] == sorted_list[1]:
            sorted_list.remove(sorted_list[0])
                
    print (sorted_list[1])

5
2 3 6 6 5
5


In [11]:
# Nested Lists
if __name__ == '__main__':
    names = []
    scores = []

    for _ in range(int(input())):
        name = input()
        score = float(input())
        names.append(name)
        scores.append(score)
records = []
for n in range (len(names)):
    records.append ([names[n], scores[n]])

sorted_scores= sorted(scores, reverse = False)
while sorted_scores[0] == sorted_scores[1]:
    sorted_scores.remove(sorted_scores[0])
second_low_value = sorted_scores [1]

for sublist in (sorted(records)):
    if sublist[1]==second_low_value:
        print (sublist[0])


5
Harry 37.21 Berry 37.21 Tina 37.2 Akriti 41 Harsh 39
4
4
5
545
545
54
5
55
52
4
54


In [13]:
# Finding the percentage
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

for key,value in student_marks.items():
    if key == query_name:
        
        mean = sum(value) / len (value)
        print ('{:.2f}'.format(mean))


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


In [14]:
# Lists
if __name__ == '__main__':
    N = int(input())
    mylist = []
    for i in range (N):
        command = input().split()
        if command [0] == "insert":
            mylist.insert(int (command[1]), int(command [2]))
        elif command [0] == "print":
            print (mylist)
        elif command [0] == "remove":
            mylist.remove(int (command[1]))
        elif command [0] == "append":
            mylist.append(int(command[1]))
        elif command [0] == "sort":
            mylist.sort()
        elif command [0] == "pop":
            mylist.pop()
        else: 
            mylist.reverse()

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


In [15]:
# Tuples
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    mytuple = tuple(integer_list)
    print (hash(mytuple))

2
1 2
-3550055125485641917


# Strings

In [22]:
# sWAP cASE
def swap_case(s):
    return s.swapcase()
if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com
hACKERrANK.COM


In [17]:
# String Split and Join
def split_and_join(line):
    split = line.split (" ")
    join = "-".join(split)
    return join
    # write your code here

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)


this is a string
this-is-a-string


In [23]:
# What's Your Name?
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    print ("Hello", first, last + "! You just delved into python.")
    return 0
    # Write your code here
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross
Taylor
Hello Ross Taylor! You just delved into python.


In [20]:
# Mutations
def mutate_string(string, position, character):
    mylist = list (string)
    mylist [position] = character
    string = "".join(mylist)
    return string
if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


In [24]:
# Find a string
def count_substring(string, sub_string):
    count = 0
    for i in range (0, len (string)+1):
        if string[i : i + len(sub_string)] == sub_string:
                count = count +1

    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


In [26]:
# String Validators
if __name__ == '__main__':
    s = input()
    mylist=list(s)
    a=0
    b=0
    c=0
    d=0
    e=0
    
    for i in mylist:
        if (i.isalnum()):
            a=a+1
        if (i.isalpha()):
            b=b+1
        if (i.isdigit()):
            c=c+1
        if (i.islower()):
            d=d+1
        if (i.isupper()):
            e=e+1
    print (a>0)
    print (b>0)
    print (c>0)
    print(d>0)
    print (e>0)
    
# I am pretty sure there is a more efficient way but this was the easiest way
#for me.

qAc
True
True
False
True
True


In [27]:
# Text Alignment
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))


5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


In [28]:
# Text Wrap
import textwrap

def wrap(string, max_width):
    new_string = textwrap.fill(string, width=max_width)
    return new_string

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


In [29]:
# Designer Door Mat
# Enter your code here. Read input from STDIN. Print output to STDOUT
inputhere=input()
n, m = map(int, inputhere.split())
c=".|."
for i in range(1,int (n-1),2):
    print((c*i).center(m, "-"))
    
print ("WELCOME".center(m,"-"))

for j in range ((int(n-2)), 0, -2):
    print((c*j).center(m, "-"))

9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


In [30]:
# String Formatting
def print_formatted(number):
    width = len(bin(number)[2:]) #this line was written with the help of chatgpt
    for i in range(1,number+1):
        dec= str(i). rjust(width)
        octal = oct(i)[2:].rjust(width)
        hexa = hex(i)[2:].upper().rjust(width)
        binary = bin(i)[2:].rjust(width)
        print (dec, octal, hexa, binary)

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


In [33]:
# Capitalize!
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    words = []
    for word in s.split(" "):
        new=word.capitalize()
        words.append(new)
    return " ".join(words)

if __name__ == '__main__':
#    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

#    fptr.write(result + '\n')

#    fptr.close()

chris alan


In [34]:
# The Minion Game
def minion_game(string):
    # your code goes here
    consonants = "BCDFGHJKLMNPQRSTVWXYZ"
    all_letters = []
    stuart_count = 0
    kevin_count = 0
    sub_strings = []
    matching_substrings= []
    sub_strings_kev = []
    matching_substrings_kev = set()
    
    for letter in string:
        if letter.isalpha():
            all_letters.append(letter)
    for i in all_letters:
        if i in consonants:
            sub_string = i
            sub_strings.append (i)
            position = all_letters.index(i)
            new_position = position+1   
            for k in range(new_position, len (all_letters)):
                sub_string = sub_string + all_letters[new_position]
                new_position = new_position +1
                sub_strings.append (sub_string)
    unique_strings = list(set(sub_strings))
    
    for sub in unique_strings:
        for j in range(len(string) - len(sub) + 1):
            if string[j:j + len(sub)] == sub:
                stuart_count += 1
                matching_substrings.append(sub)

        else:
            sub_string_kev = i
            sub_strings_kev.append (i)
            position_kev = all_letters.index(i)
            new_position_kev = position_kev+1   
            for k in range(new_position_kev, len (all_letters)):
                sub_string_kev = sub_string_kev + all_letters[new_position_kev]
                new_position_kev = new_position_kev +1
                sub_strings_kev.append (sub_string_kev)
    unique_strings_kev = list(set(sub_strings_kev))
    unique_strings_kev = list(set(unique_strings_kev))
    for sub_kev in unique_strings_kev:
        for m in range(len(string) - len(sub_kev) + 1):
            if string[m:m + len(sub_kev)] == sub_kev:
                kevin_count += 1
                matching_substrings_kev.add(sub_kev)
    matching_substrings_kev_list = list(matching_substrings_kev)

    if stuart_count > kevin_count:
        print ("Stuart", stuart_count)
    elif kevin_count > stuart_count:
        print ("Kevin", kevin_count)
    else:
        print ("Draw")
            
if __name__ == '__main__':
    s = input()
    minion_game(s)

BANANA
Stuart 12


In [35]:
# Merge the Tools!
def merge_the_tools(string, k):
    # your code goes here
    substrings = []
    for i in range(0, len(string), k):
        substring = string[i:i + k] 
        substrings.append(substring) 
        unique_strings = list(set(substring))
        word = ''.join(unique_strings)
        print (word)
    return word
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
BA
AC
AD


In [37]:
# Alphabet Rangoli
def print_rangoli(size):
    # your code goes here
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    m = 4*size-3
    linelist=[]

    for i in range(size-1, -1, -1):
        reverselist=[]
        linelist.append(alphabet[i])
        concat_letters = "-".join(linelist)
        reverselist=linelist[::-1]
        concat_letters2= "-".join(reverselist[1:])
        concat =concat_letters + "-" + concat_letters2
        print (concat.center(m,"-"))

    for i in range(1, size):
        line = "-".join(alphabet[size - 1:i:-1] + alphabet[i:size]) #I asked chatgpt a few syntax for this line.
        print(line.center(m, '-'))
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


# Sets

In [38]:
# Introduction to Sets
def average(array):
    # your code goes here
    heights = set(array)
    top = sum(heights)
    bottom = len (heights)
    result = top / bottom
    return result
    
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


In [39]:
# Symmetric Difference
# Enter your code here. Read input from STDIN. Print output to STDOUT
m = int (input ())
a = input ()
n = int (input ())
b = input ()
a_lis = set(a.split ())
b_lis = set(b.split ())
difference = list ((a_lis.symmetric_difference(b_lis)))
sorted_dif = sorted(map(int, difference))

for i in sorted_dif: 
    print(i) 

4
2 4 5 9
4
2 4 11 12
5
9
11
12


In [40]:
# Set .add()
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
countries = []
unique_countries = set()
for i in range(n):
    country = input().strip()
    countries.append(country)


for j in countries:
    unique_countries.add(j)
    
print (len(unique_countries))

7
UK
China
USA
France
New Zealand
UK
France
5


In [41]:
# Set .discard(), .remove() & .pop()
n = int(input())
s = set(map(int, input().split()))
c = int (input())
a = []
for i in range (c):
    a.append(tuple (input().split(" ")))
    
for j in a:
    if j[0] == "pop":
        s.pop ()
    elif j[0] == "remove":
        s.remove(int(j[1]))
    else: 
        s.discard(int(j[1]))
print (sum(s))

3
1 2 3 4 5 6 7 8 9
3
pop
remove 9
discard 9
35


In [42]:
# Set .union() Operation
# Enter your code here. Read input from STDIN. Print output to STDOUT
e_count = int (input())
e = set(map(int, input().split()))
f_count = int (input())
f = set(map(int, input().split()))

print (len(e.union(f)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


In [43]:
# Set .intersection() Operation
# Enter your code here. Read input from STDIN. Print output to STDOUT
e_count = int (input())
e = set(map(int, input().split()))
f_count = int (input())
f = set(map(int, input().split()))

print (len(e.intersection(f)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


In [44]:
# Set .difference() Operation
# Enter your code here. Read input from STDIN. Print output to STDOUT
e_count = int (input())
e = set(map(int, input().split()))
f_count = int (input())
f = set(map(int, input().split()))

print (len(e.difference(f)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


In [45]:
# Set .symmetric_difference() Operation
# Enter your code here. Read input from STDIN. Print output to STDOUT
e_count = int (input())
e = set(map(int, input().split()))
f_count = int (input())
f = set(map(int, input().split()))

print (len(e.symmetric_difference(f)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


In [46]:
# Set Mutations
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = int (input ())
b = set(input().split())

n = int (input ())
for i in range(n):
    command = input().split()
    c = set(input().split())
    if command[0] == "intersection_update":
        b.intersection_update(c)
    elif command[0] == "update":
        b.update(c)
    elif command[0] == "symmetric_difference_update":
        b.symmetric_difference_update(c)
    else: 
        b.difference_update(c)
el_sum = 0
for j in b:
    el_sum = el_sum + int(j)

print(el_sum)

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10





IndexError: list index out of range

In [47]:
# The Captain's Room
# Enter your code here. Read input from STDIN. Print output to STDOUT
K = int (input())
rooms = list(map(int, input().split()))
all_rooms = set()
unique_rooms = set(rooms)
for i in rooms:
    if i in all_rooms:
        unique_rooms.discard(i)
    else:
        unique_rooms.add(i)
        all_rooms.add(i)
cap_room = unique_rooms.pop()
print (cap_room)


ValueError: invalid literal for int() with base 10: ''

In [48]:
# Check Subset
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int (input ())
for t in range (T):
    A = int(input())
    A_el = set(map(int, input().split()))
    B = int(input())
    B_el = set(map(int, input().split()))
    if A_el.issubset(B_el):
        print ("True")
    else:
        print ("False")

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [49]:
# Check Strict Superset
# Enter your code here. Read input from STDIN. Print output to STDOUT
A = set(map(int, input().split()))
n = int (input())
for i in range (n):
    other_sets = set(map(int, input().split()))
    if not A.issuperset(other_sets):
        print ("False")
        break
else:
    print ("True")

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


# Collections

In [50]:
# collections.Counter()
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import Counter
X = int (input ())
sizes = list(map(int, input().split()))
available = Counter(sizes)
N = int (input ())
earned = 0
for i in range (N):
    desired = input ().split ()
    if available[int (desired[0])]:
        earned = earned + int (desired [1])
        available[int (desired[0])] = available[int (desired[0])]-1

        
print (earned)

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


In [51]:
# DefaultDict Tutorial
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import defaultdict

first_line = list(map(int, input().split()))
n = first_line[0]
m = first_line [1]
group_a = []
group_b = []
for i in range (n):
    group_a_read = list(input().strip())
    group_a.append(group_a_read)
for i in range (m):
    group_b_read = list(input().strip())
    group_b.append(group_b_read)

d = defaultdict(list)
d["group_a"].append(group_a)
d["group_b"].append (group_b)

for i, word in enumerate(group_a, start=1):

    d[str(word)].append(i)
for word in group_b:
    if str(word) in d:
        print(' '.join(map(str, d[str(word)])))
    else:
        print(-1)


5 2
a
a
b
a
b
a
b
1 2 4
3 5


In [52]:
# Collections.namedtuple()
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import namedtuple

N = int (input ())
columns = input().split()
Student = namedtuple ("Student",columns)
students = []
line_sum = 0
for i in (range (N)):
    lines = input().split()
    students = Student(*lines) # i looked this line from the "Discussions" page.
    line_sum = line_sum + int (students.MARKS)
print (line_sum / N)

5
ID         MARKS      NAME       CLASS
1          97         Raymond    7
2          50         Steven     4
3          91         Adrian     9
4          72         Stewart    5
5          80         Peter      6
78.0


In [53]:
# Collections.OrderedDict()
# Enter your code here. Read input from STDIN. Print output to STDOUT 
from collections import OrderedDict

n = int(input())

ordered_dic = OrderedDict()

for i in range(n):
    elements = input().split()
    item = " ".join(elements[:-1])
    price = int(elements[-1])
    if item in ordered_dic:
        ordered_dic[item] = ordered_dic[item] +  price
    else:
        ordered_dic[item] = price
    
for i in ordered_dic:
    print(i, ordered_dic[i])

9
BANANA FRIES 12
POTATO CHIPS 30
APPLE JUICE 10
CANDY 5
APPLE JUICE 10
CANDY 5
CANDY 5
CANDY 5
POTATO CHIPS 30
BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


In [54]:
# Word Order
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import OrderedDict
my_dict = {}
n = int(input())

for i in range(n):
    word = input()
    my_dict[i] = word

values = my_dict.values()
values_set = set(list(values))
unique_count = len(values_set)

count = {}

for j in list(values):
    if j in count:
        count[j] = count [j] + 1
    else:
        count[j] = 1
count_list = list(count.values())

print (unique_count)
print (" ".join(map(str, count_list)))

4
bcdef
abcdefg
bcde
bcdef
3
2 1 1


In [55]:
# Collections.deque()
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

n = int(input())
d = deque()

for i in range(n):
    command = input().split()
    if command[0] == "append":
        d.append(int(command[1]))
    elif command[0] == "pop":
        d.pop()
    elif command[0] == "popleft":
        d.popleft()
    elif command[0] == "appendleft":
        d.appendleft(int(command[1]))

for command in d:
    print(command, end=" ")

6
append 1
append 2
append 3
appendleft 4
pop
popleft
1 2 

# Date and Time

In [56]:
# Calendar Module
# Enter your code here. Read input from STDIN. Print output to STDOUT
import calendar

n = input ().split (" ")
year = int(n[2])
month = int (n[0])
day = int (n[1])
days = {0: "MONDAY", 1: "TUESDAY", 2: "WEDNESDAY", 3: "THURSDAY", 4: "FRIDAY", 5: "SATURDAY", 6:"SUNDAY"}
day_no =calendar.weekday(year, month, day)
print (days.get(day_no))


08 05 2015
WEDNESDAY


In [58]:
# Time Delta
#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime 
# Complete the time_delta function below.
def time_delta(t1, t2):
    date1 = datetime.strptime(t1, "%a %d %b %Y %H:%M:%S %z")
    date2 = datetime.strptime(t2, "%a %d %b %Y %H:%M:%S %z")
    diff = (abs(date1-date2))
    return str(int(diff.total_seconds()))
if __name__ == '__main__':
#    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

#        fptr.write(delta + '\n')

#    fptr.close()


2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000


# Exceptions


In [59]:
# Exceptions
# Enter your code here. Read input from STDIN. Print output to STDOUT
T = int (input())
for i in range (T):
    a,b = (input().split())
    try: # i looked how to write the errors from the Discussions section
        print(int(a) // int(b))
    except ZeroDivisionError as e:
        print('Error Code:',e)
    except ValueError as v:
        print('Error Code:',v)

3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


# Built-ins

In [61]:
# Zipped!
# Enter your code here. Read input from STDIN. Print output to STDOUT
N, X = input().split()
a = list()

for i in range (int(X)):
    a.append(list(map(float,input().split())))
for j in list (zip(*a)):
    print (sum(j)/ int(X))

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


In [62]:
# Athlete Sort
#!/bin/python3

import math
import os
import random
import re
import sys

def place (arr):
    return arr[k]
    
if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
    
    sort_arr =sorted(arr, key=place)
    for i in sort_arr:
        print (' '.join(map(str, i)))

5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


In [63]:
#ginortS
# Enter your code here. Read input from STDIN. Print output to STDOUT
s = input ()
lower = list()
upper = list()
odd = list()
even = list()
for i in (list(s)):
    if i.islower():
        lower.append(i)
    elif i.isupper():
        upper.append(i)
    elif i in ["1","3","5","7","9"]:
        odd.append(i)
    else:
        even.append(i)
s1 = sorted(lower)
s2 = sorted(upper)
s3 = sorted (odd)
s4 = sorted (even)

finallist = s1 + s2 + s3 + s4
print (''.join(finallist))


Sorting1234
ginortS1324


# Python Functionals

In [65]:
# Map and Lambda Function
cube = lambda x: x**3

def fibonacci(n):

    if n <= 0:
            return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_seq = [0, 1]
        for i in range (2, n):
            fib_seq.append(fib_seq[i-1]+fib_seq[i-2]) #i looked this line from Discussions page.
        return fib_seq

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


# XML


In [66]:
# XML 1 - Find the Score
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    # your code goes here
    length = len(node.attrib)
    first_sum = 0
    for i in node:
        a = get_attr_number(i)
        first_sum = first_sum + a

    length = length + first_sum
    return (length)
   
if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

ParseError: no element found: line 1, column 0 (<string>)

In [67]:
# XML2 - Find the Maximum Depth
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    maxdepth = max(maxdepth, level+1) #at first I wrote it as "level", instead of "level+1". I corrected after looking at the Discussions part. 
    for i in elem:
        depth(i, level + 1)
    
        
    
        
if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>     <title>HackerRank</title>     <subtitle lang='en'>Programming challenges</subtitle>     <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>     <updated>2013-12-25T12:00:00</updated> </feed>





1


# Closures and Decorations

In [68]:
# Standardize Mobile Number Using Decorators
def wrapper(f):
    def fun(l):
        numbers= []
        for i in range(len(l)):
            numbers.append(l[i][-10:])
            first_half = numbers[i][0:5]
            second_half = numbers[i][5:10]
            
            numbers[i] = "+91 " + str(first_half) + " " + str(second_half)
        return f(numbers)
    return fun
    

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


In [69]:
# Decorators 2 - Name Directory
import operator
from operator import itemgetter

def person_lister(f):
    def inner(people):
        a = []
        # complete the function
        sorted_age = sorted(people, key=itemgetter(2))
        for i in range(len(people)):
            person = sorted_age[i]
            a.append(f(person))
        return a
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


# Numpy


In [70]:
# Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    my_array = numpy.array(arr, float)
    return my_array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [71]:
# Shape and Reshape
import numpy

inp = input().split(" ")
arr = numpy.array(inp, int)
shaped = numpy.reshape(arr, (3,3))

print (shaped)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
# Transpose and Flatten
import numpy
a = input().split(" ")
n = int(a[0])
m = int(a[1])
b = []

for i in range (n):
    b.append(input().split (" "))
my_arr = numpy.array(b, int)
print (my_arr.transpose())
print (my_arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [74]:
# Concatenate
import numpy
a= input().split (" ")
n = (int(a[0]))
m = (int(a[1]))
p = (int(a[2]))
b= []
for i in range (n+m):
    b.append(input ().split(" "))
my_arr = numpy.array(b, int)
    
print (my_arr)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [76]:
# Zeros and Ones
import numpy
inp = map(int, input().split(" "))
my_list = list(inp)
print (numpy.zeros((my_list), dtype = int))
print (numpy.ones((my_list), dtype = int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [77]:
# Eye and Identity
import numpy
numpy.set_printoptions(legacy="1.13")
inp = input().split(" ")
n = int (inp[0])
m = int (inp[1])
print (numpy.eye(n,m, k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [78]:
# Array Mathematics
import numpy
first_line = input().split(" ")
n = int(first_line[0])
m = int(first_line[1])

arr_a = []
arr_b = []

for i in range(n):
    a_lines = list(map(int, input().split(" ")))
    arr_a.append(a_lines)

for j in range(n):
    b_lines = list(map(int, input().split(" ")))
    arr_b.append(b_lines)

arr_a = numpy.array(arr_a)
arr_b = numpy.array(arr_b)

print((arr_a + arr_b).reshape(n, -1))
print((arr_a - arr_b).reshape(n, -1))
print((arr_a * arr_b).reshape(n, -1))
print((arr_a // arr_b).reshape(n, -1))
print((arr_a % arr_b).reshape(n, -1))
print((arr_a ** arr_b).reshape(n, -1))


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [79]:
# Floor, Ceil and Rint
import numpy
numpy.set_printoptions(legacy="1.13")

inp = list(map(float, input().split(" ")))
my_arr = numpy.array(inp)
print (numpy.floor(my_arr))
print (numpy.ceil(my_arr))
print (numpy.rint(my_arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [80]:
# Sum and Prod
import numpy
first_line = input().split(" ")
n = int(first_line[0])
m = int(first_line[1])

arr_a = []

for i in range(n):
    a_lines = list(map(int, input().split(" ")))
    arr_a.append(a_lines)
b= numpy.sum(arr_a, axis = 0)
print (numpy.prod(b))

2 2
1 2
3 4
24


In [81]:
# Min and Max
import numpy
first_line = input().split(" ")
n = int(first_line[0])
m = int(first_line[1])

arr_a = []

for i in range(n):
    a_lines = list(map(int, input().split(" ")))
    arr_a.append(a_lines)
b = numpy.min(arr_a, axis = 1)
print (numpy.max (b))

4 2
2 5
3 7
1 3
4 0
3


In [82]:
# Mean, Var, and Std
import numpy
first_line = input().split(" ")
n = int(first_line[0])
m = int(first_line[1])

arr_a = []

for i in range(n):
    a_lines = list(map(int, input().split(" ")))
    arr_a.append(a_lines)
    
print (numpy.mean(arr_a, axis = 1))
print (numpy.var(arr_a, axis = 0))
print (round(numpy.std(arr_a), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [83]:
# Dot and Cross
import numpy
n = int(input())

arr_a = []
arr_b = []

for i in range(n):
    a_lines = list(map(int, input().split(" ")))
    arr_a.append(a_lines)

for i in range(n):
    b_lines = list(map(int, input().split(" ")))
    arr_b.append(b_lines)
print (numpy.dot(arr_a,arr_b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [84]:
# Inner and Outer
import numpy
first_line = list(map(int, input().split(" ")))
second_line = list(map(int, input().split(" ")))
arr_a = numpy.array(first_line)
arr_b = numpy.array(second_line)
print (numpy.inner(arr_a,arr_b))
print (numpy.outer(arr_a,arr_b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [85]:
# Polynomials
import numpy
line = list(map(float, input().split(" ")))
my_arr = numpy.array(line)
x = int(input())
print (numpy.polyval(my_arr, x))

1.1 2 3
0
3.0


In [86]:
# Linear Algebra
import numpy
n = int(input())

arr_a = []

for i in range(n):
    a_lines = list(map(float, input().split(" ")))
    arr_a.append(a_lines)

print (round(numpy.linalg.det(arr_a), 2))

2
1.1 1.1
1.1 1.1
0.0
